app:
  table_refresh: 30000
games:
  EldenRing:
    back: ./back
    name: 艾尔登法环
    source: C:/Users/yf/AppData/Roaming/EldenRing
  wu-kong:
    back: ./back
    name: 黑神话悟空
    source: '%APPDATA%/wu-kong/'
windows:
  h: 400
  w: 600
