app:
  # 表格刷新时间 单位毫秒
  table_refresh: 30000

windows:
  w: 600
  h: 400
games:
  EldenRing:
    is_defuel: true
    name: '艾尔登法环'
    source: '%APPDATA%/EldenRing/'
    back: './back'
  wu-kong:
    name: "黑神话悟空"
    is_defuel: false
    source: '%APPDATA%/EldenRing2/'
    back: './back'